#include "NetworkException.h"

namespace stream {

    NetworkException::
    NetworkException(const std::string& msg) noexcept(true) :
            IoException(msg,  "NetworkException: ") {
    }

    /* Generated by compiler '= default' */
//    NetworkException::
//    NetworkException(const NetworkException& ex) noexcept(true) :
//            IoException(ex) {
//    }

}
